### ISSUE TITLE
Mapquest discontinued direct access to tiles

### ISSUE THREAD

**Issue by howellcc** [ranelpadon/ckeditor-leaflet#11]
The Mapquest provider is no longer functioning properly due to Mapquest making a change in their api.

You can read about it here: http://stackoverflow.com/questions/38315300/mapquest-direct-tile-access-discontinued

**Comment by ranelpadon** [comment]
Thanks for your feedback. I also found out this issue last weekend while trying to integrate the German language in my plugin. Note that the CKEditor Leaflet Maps uses the [**Tile Providers**](http://leaflet-extras.github.io/leaflet-providers/preview/) Leaflet plugin and they have a related issue also: https://github.com/leaflet-extras/leaflet-providers/issues/219. As per suggestion in that link, fix may entails disabling the MapQuest integration or including a mechanism for API key insertion. I'll think about it. Thanks for your StackOverflow link by the way. :)

**Comment by ranelpadon** [comment]
Fixed/handled in these commits: https://github.com/ranelpadon/ckeditor-leaflet/commit/5d0c034e2069c7af1a7b9eb2503451620593273a and 
https://github.com/ranelpadon/ckeditor-leaflet/commit/5d2a48c327a5da8bcd4885b1ee3726263975d688.
