### ISSUE TITLE
ckeditor-leaflet is not GPLv2 compatible

### ISSUE THREAD

**Issue by DevinCarlson** [ranelpadon/ckeditor-leaflet#5]
I'd like to include ckeditor-leaflet in a Drupal distribution that I'm working on but, unfortunately, the LGPL v3 license used by ckeditor-leaflet is not compatible with GPLv2 (which is what all code on Drupal.org must be licensed as, per the license policy: http://drupal.org/licensing/faq#q4).

A list of GPLv2-compatible licenses can be found at http://drupal.org/node/1475972#gplv2-compatible-licenses.

I was wondering if it would be possible to change the plugin's license or dual-license it under MIT or another permitted license.

It would be great to be able to use ckeditor-leaflet with GPLv2 projects such as Drupal, Wordpress, etc!

**Comment by ranelpadon** [comment]
Okay understood. I'll review again the licenses' variants and their implications. Thanks for the heads-up and for your interest in my project. I'll give you feedback within the day or by tomorrow.

**Comment by ranelpadon** [comment]
I've reviewed your suggested links/articles, and also I've found out that some open-source softwares have multiple licenses: [CKEditor](https://github.com/ckeditor/ckeditor-dev/blob/master/LICENSE.md), [Mura CMS](http://www.getmura.com/features/licensing/), and [MySQL](http://www.mysql.com/about/legal/licensing/oem/).  

Similar to CKEditor licensing mode, I could probably change the CKEditor Leaflet Maps' license to be applicable both for **GPL v2 or later** and **LGPL v2.1 or later**. Although I think just changing my license from **LGPL v3** to **LGPL v2.1 or later** is enough and it's the minimum change needed for my project to be compatible with Drupal (and its distros), WordPress, etc. Let me know if I have understood it correctly.

**Comment by DevinCarlson** [comment]
You are correct, while Drupal is licensed as GPLv2 or later, code hosted on drupal.org can only contain resources that are GPLv2 compatible. LGPLv2.1 would satisfy this requirement where LGPLv3 does not.

Your consideration of modifying the project's license is very much appreciated.

**Comment by ranelpadon** [comment]
Okay thanks also. I've already updated the [project info](https://github.com/ranelpadon/ckeditor-leaflet) to indicate the LGPLv2.1+ license and added the license file in this [commit](https://github.com/ranelpadon/ckeditor-leaflet/commit/d38225151a391134e60debb758849e47399b9923). I'll mark this issue as **closed** then. I'll notify you also if there are plugin's improvements/updates in the future which I'm planning to do soon. Cheers. :)
