### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by smartcorestudio** [ranelpadon/ckeditor-leaflet#6]
Do you have any plans to support other languages? I'd like to add a translation but it seems that current version doesn't support it.

**Comment by ranelpadon** [comment]
Thanks for your feedback. I'll try to integrate the internationalization mechanisms also.

**Comment by ranelpadon** [comment]
I've already implemented the multilingual/localization support in my plugin, see this [commit](https://github.com/ranelpadon/ckeditor-leaflet/commit/fa6d7b739d57b0c60cba63489f37505508ac8d55).

Kindly checkout also the English translation file that I made: [en.js](https://github.com/ranelpadon/ckeditor-leaflet/blob/master/lang/en.js). 

Let me know what you think of the exposed/translated texts and if I still overlooked some translatable texts or need to remove some of them. I'll greatly appreciate if you could help me with other language translations. Note that for every language file that you add in the **lang** folder (say **es.js** file for the Spanish translation), you need to declare/activate the new language localization in the **plugin.js** file, Line 54:
```
// Declare the supported languages.
lang: 'en,es',
```

**Comment by smartcorestudio** [comment]
Thanks! I'll add a translation tomorrow!

**Comment by ranelpadon** [comment]
Okay, I've already merged the **ru.js** translation file. I forgot to mention that you need to change also the language code definition/declaration in Line 1 of **ru.js**:

from
```
CKEDITOR.plugins.setLang('leaflet', 'en', {
```

to 
```
CKEDITOR.plugins.setLang('leaflet', 'ru', {
```

Anyway, I've just modified it myself in this recent [commit](https://github.com/ranelpadon/ckeditor-leaflet/commit/b3d34b3ae64cbf68c6bc5e1086ab318a805b5072). Thanks a lot for your help and Happy New Year! I'll mark this issue closed within the day, unless you still have some concerns or you may just want to file a new issue. If you could help me in other translation files, that would be great also. Cheers. :)

**Comment by smartcorestudio** [comment]
Oh, sorry! I forgot to change language code in the header! It was my fault. Thank you for noticing this  :thumbsup:
Unfortunately I don't know other languages well enough to help you with this, but I hope other users will follow my tracks :)

**Comment by ranelpadon** [comment]
Okay no worries, other people will probably follow. I'll just indicate the translation tasks in the [CKEditor plugin page](http://ckeditor.com/addon/leaflet) and/or [README](https://github.com/ranelpadon/ckeditor-leaflet/blob/master/README.md) file so that other people could collaborate. Thanks again for your initiative. Have a good day. :)
